### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by Pigotka** [fdegier/JablotronPy#15]
When running HA addon for several days in a I encountered this error. Likely the session expired but this is handled already in addon when I get one of the supported exceptions but I should not be handling KeyError.

`2023-03-30 04:40:18.605 ERROR (MainThread) [custom_components.jablotron_cloud] Unexpected error fetching Jablotron data: 'data'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/jablotron_cloud/__init__.py", line 96, in _async_update_data
    services = await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/jablotronpy/jablotronpy.py", line 120, in get_services
    status, data = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/jablotronpy/jablotronpy.py", line 58, in _make_request
    return True, data["data"]
KeyError: 'data'`

**Comment by fdegier** [comment]
Thanks, I'll pick this up. Do you have any other issues so I can bundle them in the next release?

**Comment by Pigotka** [comment]
Only the recursion that you've fixed already.
Thank you.
